GT_FILE = "storage/GT_DATA_122_merged_filled.xlsx"
TERR_GJ = "storage/kenya_territories (1).geojson"
RTM_FILE_SUBCOUNTY = "storage/RTM_SUBCOUNTY_ANALYSIS_updated_approch (2) 1.csv"
COUNTY_GJ = "storage/kenya.geojson"
MT_FILE = "storage/MT_WHITE_SPACE_SCORE_CLEANED.xlsx"
CLUSTER_FILE = "storage/MT_CLUSTER_2_With_County.xlsx"
COMP_FILE = "storage/PWANI_COMP_STD_final_confirmed.xlsx"
TEXT_CSV = "storage/all_brands_competitive_analysis_20250530_140609.csv"
SUBCOUNTY_GJ = "storage/kenya-subcounties-simplified 1 (1).geojson"
RTM_FILE_MONTH = "storage/RTM_MONTH DATA.csv"
GEO_FILE = "storage/kenya_territories (1).geojson" 

CLUSTER_FILE = "storage/MT_CLUSTER_2_With_County.xlsx"
GEO_FILE = "storage/kenya_territories (1).geojson"
PERCENTAGE_FILE = "storage/Province Percentage 250410 (1) (1).xlsx"
TOP_LOCATION_FILE = "storage/Top_3_Brand_Locations.csv"
